# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('domicilio_particular', models.CharField(max_length=30)),
                ('cp_domicilio_particular', models.CharField(max_length=4)),
                ('domicilio_fical', models.CharField(max_length=30)),
                ('cp_domicilio_fiscal', models.CharField(max_length=4)),
                ('email', models.EmailField(max_length=254)),
                ('cuit', models.CharField(max_length=13)),
                ('codigo_area', models.CharField(max_length=4)),
                ('telefono1', models.CharField(max_length=15)),
                ('telefono2', models.CharField(max_length=15)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_baja', models.DateField(null=True)),
                ('acreditacion_brucelosis', models.CharField(max_length=15)),
                ('acreditacion_aie', models.CharField(max_length=15)),
            ],
        ),
    ]
