# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinario',
            name='acreditacion_aie',
            field=models.CharField(max_length=15, verbose_name='Numero de Acreditacion de A.I.E.'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='acreditacion_brucelosis',
            field=models.CharField(max_length=15, verbose_name='Numero de Acreditacion de Brucelosis'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='apellido',
            field=models.CharField(max_length=30, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='codigo_area',
            field=models.CharField(max_length=4, verbose_name='Codigo de Area'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='cp_domicilio_fiscal',
            field=models.CharField(max_length=4, verbose_name='Codigo Postal del Dom.Fisc'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='cp_domicilio_particular',
            field=models.CharField(max_length=4, verbose_name='Codigo Postal del Dom.Part.'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='cuit',
            field=models.CharField(max_length=13, verbose_name='C.U.I.T.'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='domicilio_fical',
            field=models.CharField(max_length=30, verbose_name='Domicilio Fiscal'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='domicilio_particular',
            field=models.CharField(max_length=30, verbose_name='Domicilio Particular'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='fecha_baja',
            field=models.DateField(null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='telefono1',
            field=models.CharField(max_length=15, verbose_name='Telefono 1'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='telefono2',
            field=models.CharField(max_length=15, verbose_name='Telefono 2'),
        ),
    ]
