# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alpha1', '0002_auto_20161103_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especie',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='especie',
            name='raza',
        ),
        migrations.AddField(
            model_name='categoriae',
            name='especie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='alpha1.Especie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raza',
            name='especie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='alpha1.Especie'),
            preserve_default=False,
        ),
    ]
