# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha1', '0003_auto_20161103_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='individuos',
            name='identificacion',
            field=models.CharField(max_length=30, verbose_name='Identificacion / N° de Caravana'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Estado Confirmado'),
        ),
        migrations.AlterField(
            model_name='solicitudanalisis',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='valoresreferencia',
            name='valorDef',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='valoresreferencia',
            name='valorRef',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
