# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha1', '0003_auto_20160915_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Especializacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Especializacion')),
            ],
        ),
        migrations.CreateModel(
            name='Explotacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Explotacion')),
            ],
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Parametro')),
                ('isInteger', models.BooleanField(verbose_name='Es Entero')),
                ('isBoolean', models.BooleanField(verbose_name='Es Verdadero/Falso')),
                ('isFloat', models.BooleanField(verbose_name='Es numero con decimales')),
                ('isString', models.BooleanField(verbose_name='Es texto')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Tecnica')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Tipo de Animal')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMuestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Tipo de Muestra')),
            ],
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='acreditacion_aie',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero de Acreditacion de A.I.E.'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='acreditacion_brucelosis',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero de Acreditacion de Brucelosis'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='telefono2',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefono 2'),
        ),
    ]
