# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha1', '0005_auto_20160915_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros',
            name='tipo_de_dato',
            field=models.CharField(choices=[('I', 'Entero'), ('B', 'Verdadero/Falso'), ('F', 'Numero con decimales'), ('S', 'Texto')], default='X', max_length=1),
            preserve_default=False,
        ),
    ]
