# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha1', '0006_parametros_tipo_de_dato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individuos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nombre')),
                ('edad', models.CharField(blank=True, max_length=2, null=True, verbose_name='Edad')),
                ('caravana', models.CharField(blank=True, max_length=10, null=True, verbose_name='N° de Caravana')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Macho'), ('H', 'Hembra'), ('X', 'NS/NC')], default='X', max_length=1, null=True, verbose_name='Sexo')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Motivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tercerizacion', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='parametros',
            name='tipo_de_dato',
            field=models.CharField(choices=[('I', 'Entero'), ('B', 'Verdadero/Falso'), ('F', 'Numero con decimales'), ('S', 'Texto')], max_length=1, verbose_name='Tipo de Dato'),
        ),
    ]
