# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha1', '0010_auto_20160916_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinario',
            name='matricula',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parametros',
            name='tipo_de_dato',
            field=models.CharField(choices=[('I', 'Entero'), ('B', 'Positivo/Negativo'), ('F', 'Numero con decimales'), ('S', 'Texto')], max_length=1, verbose_name='Tipo de Dato'),
        ),
    ]
