# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha1', '0011_auto_20160916_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinario',
            name='dni',
            field=models.CharField(default='', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='cp_domicilio_fiscal',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Codigo Postal del Dom.Fisc'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='domicilio_fical',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Domicilio Fiscal'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='telefono2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono 2'),
        ),
    ]
