# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha1', '0012_auto_20160917_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veterinario',
            old_name='domicilio_fical',
            new_name='domicilio_fiscal',
        ),
    ]
