# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alpha1', '0013_auto_20160917_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('partido', models.CharField(max_length=20)),
                ('propietario', models.CharField(max_length=30)),
                ('RENSPA', models.CharField(max_length=30)),
                ('hectareas', models.IntegerField(blank=True, null=True, verbose_name='Cant. de Hectareas')),
                ('bovinos', models.IntegerField(blank=True, null=True, verbose_name='Cant. de Hectareas')),
                ('ovinos', models.IntegerField(blank=True, null=True, verbose_name='Cant. de Hectareas')),
                ('categorias', models.ManyToManyField(to='alpha1.Categoria')),
                ('explotacion', models.ManyToManyField(to='alpha1.Explotacion')),
            ],
        ),
        migrations.CreateModel(
            name='InicioDeCarga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cant_indiv', models.IntegerField()),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha1.Establecimiento')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha1.Motivos')),
            ],
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero de Protocolo')),
                ('estado', models.BooleanField(verbose_name='Estado Confirmado')),
                ('obs', models.TextField(verbose_name='Observaciones sobre el Estado')),
                ('individuos', models.ManyToManyField(to='alpha1.Individuos')),
                ('inicioCarga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha1.InicioDeCarga', verbose_name='????')),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipoAnimal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha1.TipoAnimal')),
            ],
        ),
        migrations.CreateModel(
            name='tecXmuestraXanim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha1.TipoAnimal')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha1.TipoMuestra')),
            ],
        ),
        migrations.AddField(
            model_name='tecnicas',
            name='parametros',
            field=models.ManyToManyField(to='alpha1.Parametros'),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='especializaciones',
            field=models.ManyToManyField(to='alpha1.Especializacion'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='cp_domicilio_fiscal',
            field=models.CharField(default='1', max_length=4, verbose_name='Codigo Postal del Dom.Fisc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='cp_domicilio_particular',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Codigo Postal del Dom.Part.'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='domicilio_fiscal',
            field=models.CharField(default='domicilio', max_length=30, verbose_name='Domicilio Fiscal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='domicilio_particular',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Domicilio Particular'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='matricula',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='tecxmuestraxanim',
            name='tecnica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha1.Tecnicas'),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='tecXmuest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha1.tecXmuestraXanim', verbose_name='Tecnicas'),
        ),
        migrations.AddField(
            model_name='iniciodecarga',
            name='raza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alpha1.Raza'),
        ),
        migrations.AddField(
            model_name='iniciodecarga',
            name='tipoAnimal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha1.TipoAnimal'),
        ),
        migrations.AddField(
            model_name='iniciodecarga',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha1.Veterinario'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha1.Veterinario', verbose_name='Veterinario de Cabecera'),
        ),
        migrations.AddField(
            model_name='tecnicas',
            name='tipoMuestra',
            field=models.ManyToManyField(through='alpha1.tecXmuestraXanim', to='alpha1.TipoMuestra'),
        ),
        migrations.AlterUniqueTogether(
            name='tecxmuestraxanim',
            unique_together=set([('muestra', 'tecnica', 'animal')]),
        ),
    ]
